<a href="https://colab.research.google.com/github/ronakbihani123/python_code_/blob/main/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# introduction to mahine learning -->
# how you train ur machine learning models-->

# workflow of ml-->
# data ingestion   ---> data cleaning and preprocessing-->
# model training ---> model prediction ---> model accuracy.


In [ ]:
# feature engineering ---> data clean and preprocess


In [ ]:
# 1. data dividation

In [ ]:
# df ----> input(x)  + target(y)           #x means independent data --> ex . ur roll no, ur course ,score etc on that basis we calculate cgpa which is target column (y)
# x =  x_train , x_test                    #The training set is the portion of the data used to train the machine learning model.
# y = y_train , y_test                     #The test set is a separate portion of the data that the model has never seen before.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/placement.csv")
df.head(2)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [ ]:
df.shape

(100, 3)

In [ ]:
x = df.drop( columns = ['placed'])   #input data
x.shape



(100, 2)

In [ ]:
y = df['placed']                #target data
y.shape


(100,)

In [ ]:
from sklearn.model_selection import train_test_split             #it is library of machine learning by which we can do data preprocessing  and model training


In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)                #test_size = 0.2 means i  want to keep 20% data on test side
                                                                                                         #and the remaining will be in training part
                                                                                                         #random_state = random_state is a parameter used to control the randomness of an algorithm.

In [ ]:
a = np.random.randint(1,100,3)               #random function generate random values accoding to parameter
a

array([27, 80, 78])

In [ ]:
np.random.seed(45)                            #it will basically lock the random values generated through random function
a = np.random.randint(1,100,3)
a

array([76, 31,  4])

In [ ]:
print(f"total train data : {df.shape} , x data shape : {x_train.shape} , y data shape : {y_train.shape}")
print("x_train_shape : " , x_train.shape)
print("x_test_shape : " , x_test.shape)
print("y_train_shape : " , y_train.shape)
print("y_test_shape : " , y_test)

NameError: name 'df' is not defined

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
# df.isnull().sum()

In [ ]:
df['fever'].mean()

np.float64(100.84444444444445)

In [ ]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [ ]:
df['gender'] = df['gender'].map({"Female":0 , "Male":1})

In [ ]:
df['cough'] = df['cough'].map({"Mild":0   , "Strong":1 })
df['city'] = df['city'].map({"Kolkata" : 0,"Bangalore":1   , "Delhi":2,"Mumbai":3 })
df['has_covid'] = df['has_covid'].map({"No":0   , "Yes":1 })

In [ ]:
df

age  gender  fever  cough  city  has_covid
0    60       1  103.0      0     0          0
1    27       1  100.0      0     2          1
2    42       1  101.0      0     2          0
3    31       0   98.0      0     0          0
4    65       0  101.0      0     3          0
..  ...     ...    ...    ...   ...        ...
95   12       0  104.0      0     1          0
96   51       0  101.0      1     0          1
97   20       0  101.0      0     1          0
98    5       0   98.0      1     3          0
99   10       0   98.0      1     0          1

[100 rows x 6 columns]

In [ ]:
# task = train test split
# target column = has_covid

In [ ]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
np.round(x_train.describe(),2)

age  gender   fever  cough   city
count  80.00   80.00   80.00  80.00  80.00
mean   42.91    0.41  100.98   0.40   1.26
std    24.47    0.50    1.93   0.49   1.06
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00  100.00   0.00   0.00
50%    42.00    0.00  101.00   0.00   1.00
75%    65.00    1.00  102.00   1.00   2.00
max    84.00    1.00  104.00   1.00   3.00

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)       #fit means learn the parameter and transform means aplly on that data

In [ ]:
x_train_new = pd.DataFrame(x_train_sc , columns=x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.84  -1.56  -0.82  -1.19
25%    -0.94   -0.84  -0.51  -0.82  -1.19
50%    -0.04   -0.84   0.01  -0.82  -0.25
75%     0.91    1.19   0.53   1.22   0.70
max     1.69    1.19   1.57   1.22   1.64

In [ ]:
# normalization = >
#data --->  min_value = 0 , max_value = 1

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
from sklearn.impute import SimpleImputer                   #it does mean = 0 and next_Value gap = 1 data ko normal distribution krne ka kaam krta h

In [ ]:
si = SimpleImputer(strategy = 'mean')

In [ ]:
df['fever'] = si.fit_transform(df[['fever']])

In [ ]:
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
# encoding = transform your categorical data into numerical data

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [ ]:
x  = df.drop(columns=['has_covid'])
y = df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
np.round(x_train.describe(),2)

age  gender   fever  cough   city
count  80.00   80.00   71.00  80.00  80.00
mean   42.91    0.41  101.00   0.40   1.30
std    24.47    0.50    2.05   0.49   1.12
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00   99.50   0.00   0.00
50%    42.00    0.00  101.00   0.00   1.00
75%    65.00    1.00  103.00   1.00   2.00
max    84.00    1.00  104.00   1.00   3.00

In [ ]:
from sklearn.preprocessing import MinMaxScaler                 #data ko scaled krne ka kaam krta h jisse min = 0 or max = 1 ho jaye


In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame(x_train_mn , columns = x.columns)

In [ ]:
np.round(x_train_new.describe(),2)

age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean    0.48    0.41   0.50   0.40   0.43
std     0.31    0.50   0.34   0.49   0.37
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00   0.00
50%     0.47    0.00   0.50   0.00   0.33
75%     0.76    1.00   0.83   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00

In [ ]:
df_placement = pd.read_csv("/content/placement.csv")

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
pmn = MinMaxScaler()

In [ ]:
x_train_pmn  = pmn.fit_transform(x_train)

In [ ]:
x_train_new1 = pd.DataFrame(x_train_pmn , columns = x.columns)

In [ ]:
np.round(x_train_new1.describe(),2)

age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean    0.48    0.41   0.50   0.40   0.43
std     0.31    0.50   0.34   0.49   0.37
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00   0.00
50%     0.47    0.00   0.50   0.00   0.33
75%     0.76    1.00   0.83   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00

In [ ]:
# data  --- insurance data
# targetcol = charges
# data import --> encode ---> standardization
# data import --->encode ---> normalization

In [ ]:
insur_df = pd.read_csv("/content/insurance.csv")
insur_df.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
x = insur_df.drop(columns = ["charges"])
y = insur_df["charges"]

In [ ]:
insur_df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb1 = LabelEncoder()

In [ ]:
insur_df['sex'] = lb1.fit_transform(insur_df['sex'])

In [ ]:
insur_df['smoker'] = lb1.fit_transform(insur_df['smoker'])
insur_df['region'] = lb1.fit_transform(insur_df['region'])
insur_df['charges'] = lb1.fit_transform(insur_df['charges'])

In [ ]:
x = insur_df.drop(columns = ["charges"])
y = insur_df["charges"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
np.round(x_train.describe(),2)

age      sex      bmi  children   smoker   region
count  1070.00  1070.00  1070.00   1070.00  1070.00  1070.00
mean     39.36     0.51    30.56      1.11     0.21     1.51
std      14.07     0.50     6.04      1.22     0.40     1.12
min      18.00     0.00    15.96      0.00     0.00     0.00
25%      27.00     0.00    26.20      0.00     0.00     1.00
50%      39.50     1.00    30.21      1.00     0.00     2.00
75%      51.00     1.00    34.50      2.00     0.00     2.00
max      64.00     1.00    53.13      5.00     1.00     3.00

In [ ]:
from sklearn .preprocessing import MinMaxScaler

In [ ]:
imn= MinMaxScaler()

In [ ]:
x_train_imn  = imn.fit_transform(x_train)

In [ ]:
x_train_new2 = pd.DataFrame(x_train_imn , columns = x.columns)

In [ ]:
np.round(x_train_new1.describe(),2)

age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean    0.48    0.41   0.50   0.40   0.43
std     0.31    0.50   0.34   0.49   0.37
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.25   0.00   0.00
50%     0.47    0.00   0.50   0.00   0.33
75%     0.76    1.00   0.83   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")

In [ ]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.dropna()

In [ ]:
# ordinal encoder ---> using this method we can import multiple categorical columns together

In [ ]:
# label encoder me single single column pe apply krte h bt ordinal me multiple column encode kr skte h

In [ ]:
df = df.drop(columns = ['age', 'fever', 'city'])

In [ ]:
df.head(2)

gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['Male', 'Female'],
                              ['Mild','Strong'],
                                ['No', 'Yes']])

In [ ]:
oe.fit_transform(df)

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [1., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 1.],
       [1., 0

In [ ]:
# onehot encoding --->
# column
# has_covid [ 'no ', 'yes']  --- > 2 new column 'has_coivd_no' , 'has_covid_yes'
# 1 sub category column remove

In [ ]:
df = pd.read_csv ("covid_toy.csv")
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.dropna()

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder(drop = 'first' , sparse_output = False , dtype = np.int32)

In [ ]:
a = ohe.fit_transform(df[['gender' , 'cough', 'city' ,'has_covid']])

In [ ]:
a.shape

(100, 6)

In [ ]:

# gender  === m
# cough == m
# city = d,m,n
# has_covid = y

In [ ]:
# encoding  === get_dummies  ----> same work as one hot encoding but
# it provides you column name as well as their respective values

In [ ]:
df  = pd.read_csv("/content/covid_toy.csv")
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df = df.dropna()

In [ ]:
a = pd.get_dummies(df , columns = ['gender' , 'cough', 'city' ,'has_covid' ], drop_first = True)

In [ ]:
a =a.astype(int)

In [ ]:
a

age  fever  gender_Male  cough_Strong  city_Delhi  city_Kolkata  \
0    60    103            1             0           0             1   
1    27    100            1             0           1             0   
2    42    101            1             0           1             0   
3    31     98            0             0           0             1   
4    65    101            0             0           0             0   
..  ...    ...          ...           ...         ...           ...   
95   12    104            0             0           0             0   
96   51    101            0             1           0             1   
97   20    101            0             0           0             0   
98    5     98            0             1           0             0   
99   10     98            0             1           0             1   

    city_Mumbai  has_covid_Yes  
0             0              0  
1             0              1  
2             0              0  
3             0              0  
4             1              0  
..          ...            ...  
95            0              0  
96            0              1  
97            0              0  
98            1              0  
99            0              1  

[90 rows x 8 columns]

In [ ]:
# column transformer-->
# this is a container in which we can storre our steps of process

# columnTransformer(transformer = [[ 'constant ', 'approach/rule', 'column_name']] )
#

In [ ]:
# task -->
# covid_dataset --> divide trafrom training and testing sets
# x_train data ----> 1-1 column preprocess  ---> all column shape total

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test,y_train ,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.head(2)

age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata

In [ ]:
# manually process

In [ ]:
# adding simple imputer to fever column
si = SimpleImputer(strategy='mean')
x_train_fever = si.fit_transform(x_train[['fever']])
x_train_fever.shape

(80, 1)

In [ ]:
# OrdinalEncoder---> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])
x_train_cough.shape

(80, 1)

In [ ]:
# onehotencoding --> gender , city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_train_gender_city.shape

(80, 4)

In [ ]:
# Extracting age
x_train_age = x_train.drop(columns=['gender','fever','cough','city']).values
x_train_age.shape

(80, 1)

In [ ]:
x_train_transformed = np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
# also the test data

In [ ]:
x_train_transformed.shape

(80, 7)

In [ ]:
# we will do this same work with the help of column transformer


In [ ]:
from sklearn.compose import ColumnTransformer     #this is hoe to import column _transformer

In [ ]:
transformer = ColumnTransformer(transformers=[('tnf1',SimpleImputer(),['fever']),           #in a fever column by the help of si we fill missing values by mean,median,mode
                                               ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),      #by this process we encode our data
                                               ('tnf3',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])],remainder='passthrough')
                                                    # remainder  =  passthrough ===>
                                                    # it means rest all the column remains same

In [ ]:
a = transformer.fit_transform(x_train)

In [ ]:
a.shape

(80, 7)

In [ ]:
df = pd.read_csv("/content/insurance.csv")
df.head(2)

age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
x= df.drop(columns = ["charges"])
y = df["charges"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
x_train.head(2)
x_train.shape

(1070, 6)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
oe = OrdinalEncoder(categories=[['female', 'male'],
                                ['yes', 'no'],
                                ['southwest' , 'southeast','northwest' ,'northeast']])

In [ ]:
x_train_sex_smoker_region = oe.fit_transform(x_train[['sex','smoker','region']])
x_train_sex_smoker_region.shape


(1070, 3)

In [ ]:
x_train_sex_smoker_region

array([[0., 1., 2.],
       [0., 1., 3.],
       [0., 1., 1.],
       ...,
       [1., 1., 3.],
       [0., 0., 0.],
       [1., 1., 0.]])

In [ ]:
x_train_age_bmi_children = x_train.drop(columns=['age','bmi','children']).values
x_train_age_bmi_children.shape

(1070, 3)

In [ ]:
x_train_transformed = np.concatenate((x_train_age_bmi_children,x_train_sex_smoker_region),axis=1)

In [ ]:
x_train_transformed.shape

(1070, 6)

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

transformer = ColumnTransformer(transformers=[          #in a fever column by the help of si we fill missing values by mean,median,mode
                                               ('tnf1',OrdinalEncoder(categories=[['female', 'male'],
                                                                                  ['yes', 'no'],
                                                                                  ['southwest' , 'southeast','northwest' ,'northeast']]),
                                               ['sex', 'smoker' , 'region']),      #by this process we encode our data
                                               ],remainder='passthrough')
                                                    # remainder  =  passthrough ===>
                                                    # it means rest all the column remains same

In [ ]:
a = transformer.fit_transform(x_train)

In [ ]:
a.shape

(1070, 6)

In [ ]:
# function transformer


In [ ]:
# the function transformer is a tool in sklearn , a popular python library in ml , that allows u yo apply a specified function to the input data . the function transformer can be useful for performing custom transformation of input data in machine learning pipeline

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np.

In [ ]:
x = np.array([[1,2],[3,4]])

In [ ]:
log_transform = FunctionTransformer(np.log1p)

In [ ]:
x_transformed = log_transform.transform(x)

In [ ]:
print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
x = np.array([[1,2],[3,4]])   #create dataset

In [ ]:
def squ(x):
  return np.hstack((x,x**2))   #define a custom feature engineering function

In [ ]:
custom_transformer = FunctionTransformer(squ)         #create a function transformer to apply the custom function

In [ ]:
x_transformed  = custom_transformer.transform(x)       #apply the transformer to the input data

In [ ]:
print(x_transformed)               #view the transformed data

[[ 1  2  1  4]
 [ 3  4  9 16]]


In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [ ]:
x = np.array([[1,2],[3,4]])

In [ ]:
def my_scaling(x):           #define a custom scaling function
  return x / np.max(x)

In [ ]:
custom_transformer = FunctionTransformer(my_scaling)

In [ ]:
x_transformed  = custom_transformer.transform(x)

In [ ]:
print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [ ]:
x = np.array([[1,2],[3,np.nan]])

In [ ]:
def my_cleaning(x):
  x[np.isnan(x)] = 0
  return x

In [ ]:
custom_transformer = FunctionTransformer(my_cleaning)

In [ ]:
x_transformed = custom_transformer.transform(x)

In [ ]:
print(x_transformed)

[[nan nan]
 [nan nan]]


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/placement (1).csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/placement (1).csv'

In [ ]:
df.head(3)

cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [ ]:
x = df.drop(columns = ['placed'])
y = df["placed"]

In [ ]:
from sklearn.preprocessing import FunctionTransformer

In [ ]:
log_transform = FunctionTransformer(np.log1p)

In [ ]:
x_transformed  = log_transform.transform(x)      #apply the transformation to the dataset

In [ ]:
x_transformed

cgpa  resume_score
0   2.212660      2.017566
1   1.969906      1.819699
2   2.226783      2.288486
3   2.064328      2.112635
4   2.142416      2.116256
..       ...           ...
95  1.991976      1.998774
96  2.222459      2.170196
97  2.034706      2.172476
98  2.212660      1.891605
99  1.958685      2.029463

[100 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/covid_toy.csv")
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si = SimpleImputer(strategy='mean')

In [ ]:
df['fever'] = si.fit_transform(df[['fever']])

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df.head(2)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
oe = OrdinalEncoder(categories=[['Male', 'Female'],
                              ['Mild','Strong'],
                              ["Kolkata" , "Delhi" , "Mumbai" , "Bangalore"]])

In [ ]:
df[['gender','cough','city']] = oe.fit_transform(df[['gender','cough','city',]])

In [ ]:
# df = df.drop(columns ='city')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
df["has_covid"] = le.fit_transform(df["has_covid"])

In [ ]:
df

age  gender  fever  cough  city  has_covid
0    60     0.0  103.0    0.0   0.0          0
1    27     0.0  100.0    0.0   1.0          1
2    42     0.0  101.0    0.0   1.0          0
3    31     1.0   98.0    0.0   0.0          0
4    65     1.0  101.0    0.0   2.0          0
..  ...     ...    ...    ...   ...        ...
95   12     1.0  104.0    0.0   3.0          0
96   51     1.0  101.0    1.0   0.0          1
97   20     1.0  101.0    0.0   3.0          0
98    5     1.0   98.0    1.0   2.0          0
99   10     1.0   98.0    1.0   0.0          1

[100 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import FunctionTransformer;

In [ ]:
log_transformer = FunctionTransformer(np.log1p)

In [ ]:
x_transformed = log_transformer.transform(x)

In [ ]:
x_transformed

age    gender     fever     cough      city
0   4.110874  0.000000  4.644391  0.000000  0.000000
1   3.332205  0.000000  4.615121  0.000000  0.693147
2   3.761200  0.000000  4.624973  0.000000  0.693147
3   3.465736  0.693147  4.595120  0.000000  0.000000
4   4.189655  0.693147  4.624973  0.000000  1.098612
..       ...       ...       ...       ...       ...
95  2.564949  0.693147  4.653960  0.000000  1.386294
96  3.951244  0.693147  4.624973  0.693147  0.000000
97  3.044522  0.693147  4.624973  0.000000  1.386294
98  1.791759  0.693147  4.595120  0.693147  1.098612
99  2.397895  0.693147  4.595120  0.693147  0.000000

[100 rows x 5 columns]